language: generic
sudo: required

services: 
 - docker

before_install:
 - docker build -t l-ghost/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true l-ghost/docker-react npm run test
